accounts/urls.py
from accounts.views import AccountCreateView, AccountLoginView, AccountLogoutView, AccountPasswordChangeView, \
    AccountUpdateView

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordChangeView.as_view(), name='password'),
]

core/urls.py
from django.urls import path

from core.views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

django_hillel/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

from student.views import hello, get_random


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),
    path('students/', include('student.urls')),
    path('group/', include('group.urls')),
    path('teachers/', include('teacher.urls')),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

group/urls.py
from django.urls import path
from group.views import GroupCreateView, GroupDeleteView, GetGroupListView, GroupUpdateView

app_name = 'group'

urlpatterns = [
    path('', GetGroupListView.as_view(), name='allgroups'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('edit/<pk>', GroupUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', GroupDeleteView.as_view(), name='delete'),
]

student/urls.py
from django.urls import path

from student.views import StudentCreateView, StudentListView, StudentEditView, generate_students

app_name = 'students'

urlpatterns = [
    path('generate-students/', generate_students),
    path('', StudentListView.as_view(), name='allstudent'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('edit/<pk>', StudentEditView.as_view(), name='edit'),
]

teacher/urls.py
from django.urls import path

from teacher.views import TeacherCreateView, TeacherDeleteView, TeacherListView, TeacherUpdateView

app_name = 'teacher'

urlpatterns = [
    path('',  TeacherListView.as_view(), name='allTeacher'),
    path('create/', TeacherCreateView.as_view(), name='create'),
    path('edit/<int:id>', TeacherUpdateView.as_view(), name='edit'),
    path('delete/<int:id>', TeacherDeleteView.as_view(), name='delete'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% block title %}
        <title>LMS</title>
{% endblock %}
</head>
<body>


<nav class="navbar navbar-default navbar-fixed-top navbar-expand-lg navbar-dark bg-primary font-weight-bold ">
  <div class="container">
  <a class="navbar-brand" href="{% url 'core:index' %}">LMS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Students
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'students:allstudent' %}">Show students</a>
          <a class="dropdown-item" href="{% url 'students:create' %}">Create student</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'group:allgroups' %}">Groups</a>
      </li>
              <li class="nav-item">
        <a class="nav-link" href="{% url 'teacher:allTeacher' %}">Teachers</a>
      </li>
    </ul>
      <ul class="navbar-nav ">

                {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                </li>
                    <li class="img-circle.vert">
                    <img class="rounded-circle p-1 m-1" width="40" height="40" src=" {{ user.profile.image.url }} ">
                </li>


                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                </li>

                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>

                {% endif %}

            </ul>

  </div>
  </div>
</nav>
    {% include 'includes/messages.html' %}
  <div class="container">
            <div class="border rounded text-center p-3 m-3 mb-5 bg-light shadow">
                {% block header %}
                    <h1>
                        <p>{{ description }}</p>
                    </h1>
                {% endblock %}
            </div>
            {% block content %}
            {% endblock %}
  </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
  <h1 class="display-4">Hello, user!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="{% url 'students:allstudent' %}" role="button">Students list</a>
</div>
{% endblock %}

templates/pagination.html
<nav aria-label="Navigator>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
        {% endif %}

        <li class="page-link" >
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last</a></li>
        {% endif %}
    </ul>
</nav>